### ISSUE TITLE
Display options issues

### ISSUE THREAD

**Issue by ktanev** [picturae/mediabank-wordpress-plugin#1]
1. **Gallery mode** work - ✅ 
1.1 **Gallery mode** doesn't work when using only one mode. Check only Map for example. 
2. **Detail modes**  work ✅ 
3. Enabling **Endless scrolling** remove the pagination ✅ 
4. Enabling/Disabling **Sorting**  work ✅
5. **Watermark url** doesn't work 
6. **Search help url** work ✅
7. **Topviewer buttons** doesn't work
8. **Perm Links** doesn't work ✅
9. Refresh of the main view results in not-found

**Comment by Pin0** [comment]
Closed, because we are no longer maintaining this repository
